"""Add source_handle and target_handle to workflow_edges

Revision ID: 12c3dc1a833f
Revises: d6338901109d
Create Date: 2025-10-14 02:20:39.567779

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '12c3dc1a833f'
down_revision: Union[str, None] = 'd6338901109d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add source_handle and target_handle columns to workflow_edges
    op.add_column('workflow_edges', sa.Column('source_handle', sa.String(), nullable=True))
    op.add_column('workflow_edges', sa.Column('target_handle', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Remove source_handle and target_handle columns from workflow_edges
    op.drop_column('workflow_edges', 'target_handle')
    op.drop_column('workflow_edges', 'source_handle')
    # ### end Alembic commands ###
