"""Change x_pos and y_pos to Float in workflow_nodes

Revision ID: d6338901109d
Revises: 7033299595ff
Create Date: 2025-10-14 01:03:42.395945

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd6338901109d'
down_revision: Union[str, None] = '7033299595ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Change x_pos and y_pos from INTEGER to FLOAT
    op.alter_column('workflow_nodes', 'x_pos',
                    existing_type=sa.INTEGER(),
                    type_=sa.Float(),
                    existing_nullable=True)
    op.alter_column('workflow_nodes', 'y_pos',
                    existing_type=sa.INTEGER(),
                    type_=sa.Float(),
                    existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Revert x_pos and y_pos back to INTEGER
    op.alter_column('workflow_nodes', 'y_pos',
                    existing_type=sa.Float(),
                    type_=sa.INTEGER(),
                    existing_nullable=True)
    op.alter_column('workflow_nodes', 'x_pos',
                    existing_type=sa.Float(),
                    type_=sa.INTEGER(),
                    existing_nullable=True)
    # ### end Alembic commands ###
